# config/packages/security.yaml
security:
  firewalls:
    main:
      # Utiliser l'authentification par formulaire par défaut
      form_login:
        login_path: app_login # Chemin de la route pour le formulaire de connexion
        check_path: app_login_check # Chemin de la route pour la vérification du formulaire de connexion
      # Redirige vers l'URL de la page de succès après l'authentification
      logout:
        path: app_logout
        target: /login

  password_hashers:

    App\Entity\User:
      # the new hasher, along with its options
      algorithm: auto



  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email